@hostname =  http://127.0.0.1:8000

### GET  // Featch All Services
GET {{hostname}}/api/services HTTP/1.1
Accept: application/json


### POST  // Create Service
POST {{hostname}}/api/services HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "name": "S1",
    "price": 200,
    "status": "Available",
    "type": "Software Development"
}

### GET  // GET Service
GET {{hostname}}/api/services/2 HTTP/1.1
Accept: application/json


### PUT  // Update Service
PUT {{hostname}}/api/services/1 HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "name": "S2",
    "price": 200,
    "status": "Available",
    "type": "Software Development"
}

### POST  // Check if service if available in given date
POST {{hostname}}/api/services/1/availability HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "when": "2023-10-10"
}

### DELETE  // DELETE Service
DELETE {{hostname}}/api/services/1 HTTP/1.1
Accept: application/json
