@hostname =  http://127.0.0.1:8000

### GET REQUEST // View All Transactions
GET {{hostname}}/api/transactions HTTP/1.1
Accept: application/json

### GET REQUEST // View Sale by ID
GET {{hostname}}/api/transactions/1 HTTP/1.1
Accept: application/json

### POST REQUEST // Create Sale
POST {{hostname}}/api/transactions HTTP/1.1
Content-Type: application/json
Connection: keep-alive
Accept: */*


### PUT REQUEST // Edit Sale by ID
PUT {{hostname}}/api/transactions/1 HTTP/1.1
Content-Type: application/json
Connection: keep-alive
Accept: */*

{
 "sale_id": "distinctio",
  "amount_rendered": "ZYYQT301",
  "change": "YYMPL101"
}

### DELETE REQUEST // Delete Sale by ID
DELETE   {{hostname}}/api/transactions/1 HTTP/1.1
Content-Type: application/json
Connection: keep-alive
Accept: */*

// Services apis

### GET  // Featch All Services
GET {{hostname}}/api/services HTTP/1.1
Accept: application/json


### POST  // Create Service
POST {{hostname}}/api/services HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "name": "S1",
    "price": 200,
    "status": "Available"
}

### GET  // GET Service
GET {{hostname}}/api/services/2 HTTP/1.1
Accept: application/json


### PUT  // Update Service
PUT {{hostname}}/api/services/1 HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "name": "S2",
    "price": 200,
    "status": "Available"
}

### DELETE  // DELETE Service
DELETE {{hostname}}/api/services/1 HTTP/1.1
Accept: application/json

